[2024-02-08T16:12:33.552+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yellow_cabs_dag.yellow_cabs_upload manual__2024-02-08T16:12:32.881772+00:00 [queued]>
[2024-02-08T16:12:33.555+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yellow_cabs_dag.yellow_cabs_upload manual__2024-02-08T16:12:32.881772+00:00 [queued]>
[2024-02-08T16:12:33.555+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-02-08T16:12:33.560+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): yellow_cabs_upload> on 2024-02-08 16:12:32.881772+00:00
[2024-02-08T16:12:33.563+0000] {standard_task_runner.py:60} INFO - Started process 99 to run task
[2024-02-08T16:12:33.565+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'yellow_cabs_dag', 'yellow_cabs_upload', 'manual__2024-02-08T16:12:32.881772+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/yellow_cabs_project.py', '--cfg-path', '/tmp/tmp64dgsk8a']
[2024-02-08T16:12:33.566+0000] {standard_task_runner.py:88} INFO - Job 27: Subtask yellow_cabs_upload
[2024-02-08T16:12:33.716+0000] {task_command.py:423} INFO - Running <TaskInstance: yellow_cabs_dag.yellow_cabs_upload manual__2024-02-08T16:12:32.881772+00:00 [running]> on host 49b06be5e1b6
[2024-02-08T16:12:33.743+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='yellow_cabs_dag' AIRFLOW_CTX_TASK_ID='yellow_cabs_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-02-08T16:12:32.881772+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-08T16:12:32.881772+00:00'
[2024-02-08T16:12:40.366+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/yellow_cabs_project.py", line 24, in yellow_cabs_upload
    new_table.to_sql('yellow_cabs_report', con=db, if_exist='append', index=False)
TypeError: to_sql() got an unexpected keyword argument 'if_exist'
[2024-02-08T16:12:40.379+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=yellow_cabs_dag, task_id=yellow_cabs_upload, execution_date=20240208T161232, start_date=20240208T161233, end_date=20240208T161240
[2024-02-08T16:12:40.403+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 27 for task yellow_cabs_upload (to_sql() got an unexpected keyword argument 'if_exist'; 99)
[2024-02-08T16:12:40.429+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-08T16:12:40.438+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
