[2024-01-31T20:47:49.051+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yellow_cabs_dag.yellow_cabs_upload manual__2024-01-31T20:39:11.916517+00:00 [queued]>
[2024-01-31T20:47:49.055+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yellow_cabs_dag.yellow_cabs_upload manual__2024-01-31T20:39:11.916517+00:00 [queued]>
[2024-01-31T20:47:49.055+0000] {taskinstance.py:2171} INFO - Starting attempt 2 of 2
[2024-01-31T20:47:49.059+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): yellow_cabs_upload> on 2024-01-31 20:39:11.916517+00:00
[2024-01-31T20:47:49.062+0000] {standard_task_runner.py:60} INFO - Started process 86 to run task
[2024-01-31T20:47:49.064+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'yellow_cabs_dag', 'yellow_cabs_upload', 'manual__2024-01-31T20:39:11.916517+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/yellow_cabs_project.py', '--cfg-path', '/tmp/tmp52pycdg5']
[2024-01-31T20:47:49.066+0000] {standard_task_runner.py:88} INFO - Job 44: Subtask yellow_cabs_upload
[2024-01-31T20:47:49.087+0000] {task_command.py:423} INFO - Running <TaskInstance: yellow_cabs_dag.yellow_cabs_upload manual__2024-01-31T20:39:11.916517+00:00 [running]> on host 8ff05e883b9e
[2024-01-31T20:47:49.205+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='yellow_cabs_dag' AIRFLOW_CTX_TASK_ID='yellow_cabs_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-01-31T20:39:11.916517+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-31T20:39:11.916517+00:00'
[2024-01-31T20:48:07.378+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/yellow_cabs_project.py", line 37, in yellow_cabs_upload
    df_iter = pd.read_csv('/Users/oluwaseyi/Desktop/YellowCabs_Project/csv_file.csv', index_col=False, chunksize=200000)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/Users/oluwaseyi/Desktop/YellowCabs_Project/csv_file.csv'
[2024-01-31T20:48:07.386+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=yellow_cabs_dag, task_id=yellow_cabs_upload, execution_date=20240131T203911, start_date=20240131T204749, end_date=20240131T204807
[2024-01-31T20:48:07.420+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 44 for task yellow_cabs_upload ([Errno 2] No such file or directory: '/Users/oluwaseyi/Desktop/YellowCabs_Project/csv_file.csv'; 86)
[2024-01-31T20:48:07.463+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-31T20:48:07.559+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
