[2024-02-05T16:16:06.786+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yellow_cabs_dag.yellow_cabs_upload manual__2024-02-05T16:16:06.157596+00:00 [queued]>
[2024-02-05T16:16:06.789+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yellow_cabs_dag.yellow_cabs_upload manual__2024-02-05T16:16:06.157596+00:00 [queued]>
[2024-02-05T16:16:06.790+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-02-05T16:16:06.795+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): yellow_cabs_upload> on 2024-02-05 16:16:06.157596+00:00
[2024-02-05T16:16:06.798+0000] {standard_task_runner.py:60} INFO - Started process 186 to run task
[2024-02-05T16:16:06.800+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'yellow_cabs_dag', 'yellow_cabs_upload', 'manual__2024-02-05T16:16:06.157596+00:00', '--job-id', '142', '--raw', '--subdir', 'DAGS_FOLDER/yellow_cabs_project.py', '--cfg-path', '/tmp/tmpa36iqqo8']
[2024-02-05T16:16:06.801+0000] {standard_task_runner.py:88} INFO - Job 142: Subtask yellow_cabs_upload
[2024-02-05T16:16:06.822+0000] {task_command.py:423} INFO - Running <TaskInstance: yellow_cabs_dag.yellow_cabs_upload manual__2024-02-05T16:16:06.157596+00:00 [running]> on host 66814aa8a277
[2024-02-05T16:16:06.980+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='yellow_cabs_dag' AIRFLOW_CTX_TASK_ID='yellow_cabs_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-02-05T16:16:06.157596+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-05T16:16:06.157596+00:00'
[2024-02-05T16:16:26.452+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/yellow_cabs_project.py", line 35, in yellow_cabs_upload
    df_iter = pd.read_csv('/Users/oluwaseyi/Desktop/YellowCabs_Project/csv_file.csv',
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/Users/oluwaseyi/Desktop/YellowCabs_Project/csv_file.csv'
[2024-02-05T16:16:26.460+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=yellow_cabs_dag, task_id=yellow_cabs_upload, execution_date=20240205T161606, start_date=20240205T161606, end_date=20240205T161626
[2024-02-05T16:16:26.499+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 142 for task yellow_cabs_upload ([Errno 2] No such file or directory: '/Users/oluwaseyi/Desktop/YellowCabs_Project/csv_file.csv'; 186)
[2024-02-05T16:16:26.548+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-05T16:16:26.653+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
