[2024-01-26T20:02:50.486+0000] {scheduler_job_runner.py:1586} WARNING - Marking task instance <TaskInstance: yellow_cabs_dag.yellow_cabs_upload manual__2024-01-26T19:51:30.429536+00:00 [queued]> stuck in queued as failed. If the task instance has available retries, it will be retried.
[2024-01-26T20:02:50.596+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: yellow_cabs_dag.yellow_cabs_upload manual__2024-01-26T19:51:30.429536+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
