[2024-02-05T16:09:23.960+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yellow_cabs_dag.yellow_cabs_upload scheduled__2024-02-03T00:00:00+00:00 [queued]>
[2024-02-05T16:09:23.972+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yellow_cabs_dag.yellow_cabs_upload scheduled__2024-02-03T00:00:00+00:00 [queued]>
[2024-02-05T16:09:23.972+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-02-05T16:09:23.981+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): yellow_cabs_upload> on 2024-02-03 00:00:00+00:00
[2024-02-05T16:09:23.985+0000] {standard_task_runner.py:60} INFO - Started process 53 to run task
[2024-02-05T16:09:23.993+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'yellow_cabs_dag', 'yellow_cabs_upload', 'scheduled__2024-02-03T00:00:00+00:00', '--job-id', '122', '--raw', '--subdir', 'DAGS_FOLDER/yellow_cabs_project.py', '--cfg-path', '/tmp/tmppriqot6r']
[2024-02-05T16:09:24.004+0000] {standard_task_runner.py:88} INFO - Job 122: Subtask yellow_cabs_upload
[2024-02-05T16:09:24.204+0000] {task_command.py:423} INFO - Running <TaskInstance: yellow_cabs_dag.yellow_cabs_upload scheduled__2024-02-03T00:00:00+00:00 [running]> on host 66814aa8a277
[2024-02-05T16:09:24.246+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='yellow_cabs_dag' AIRFLOW_CTX_TASK_ID='yellow_cabs_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-02-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-03T00:00:00+00:00'
[2024-02-05T16:09:54.231+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/yellow_cabs_project.py", line 35, in yellow_cabs_upload
    df_iter = pd.read_csv('/Users/oluwaseyi/Desktop/YellowCabs_Project/csv_file.csv',
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/Users/oluwaseyi/Desktop/YellowCabs_Project/csv_file.csv'
[2024-02-05T16:09:54.244+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=yellow_cabs_dag, task_id=yellow_cabs_upload, execution_date=20240203T000000, start_date=20240205T160923, end_date=20240205T160954
[2024-02-05T16:09:54.253+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 122 for task yellow_cabs_upload ([Errno 2] No such file or directory: '/Users/oluwaseyi/Desktop/YellowCabs_Project/csv_file.csv'; 53)
[2024-02-05T16:09:54.351+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-05T16:09:54.361+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-02-05T18:11:20.147+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yellow_cabs_dag.yellow_cabs_upload scheduled__2024-02-03T00:00:00+00:00 [queued]>
[2024-02-05T18:11:20.166+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yellow_cabs_dag.yellow_cabs_upload scheduled__2024-02-03T00:00:00+00:00 [queued]>
[2024-02-05T18:11:20.167+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-02-05T18:11:20.180+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): yellow_cabs_upload> on 2024-02-03 00:00:00+00:00
[2024-02-05T18:11:20.184+0000] {standard_task_runner.py:60} INFO - Started process 116 to run task
[2024-02-05T18:11:20.192+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'yellow_cabs_dag', 'yellow_cabs_upload', 'scheduled__2024-02-03T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/yellow_cabs_project.py', '--cfg-path', '/tmp/tmp89rc_fts']
[2024-02-05T18:11:20.195+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask yellow_cabs_upload
[2024-02-05T18:11:20.227+0000] {task_command.py:423} INFO - Running <TaskInstance: yellow_cabs_dag.yellow_cabs_upload scheduled__2024-02-03T00:00:00+00:00 [running]> on host 49b06be5e1b6
[2024-02-05T18:11:20.798+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='yellow_cabs_dag' AIRFLOW_CTX_TASK_ID='yellow_cabs_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-02-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-03T00:00:00+00:00'
[2024-02-05T18:11:39.208+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/yellow_cabs_project.py", line 32, in yellow_cabs_upload
    pq_table.to_csv(output_file_path, index=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 3772, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/format.py", line 1186, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/csvs.py", line 240, in save
    with get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 737, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 600, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/opt/***/dags/yellow_cabs_project.py'
[2024-02-05T18:11:39.214+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=yellow_cabs_dag, task_id=yellow_cabs_upload, execution_date=20240203T000000, start_date=20240205T181120, end_date=20240205T181139
[2024-02-05T18:11:39.236+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5 for task yellow_cabs_upload (Cannot save file into a non-existent directory: '/opt/***/dags/yellow_cabs_project.py'; 116)
[2024-02-05T18:11:39.302+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-05T18:11:39.446+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
