[2024-02-09T18:21:55.317+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yellow_cabs_dag.yellow_cabs_upload manual__2024-02-09T18:21:53.472322+00:00 [queued]>
[2024-02-09T18:21:55.331+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yellow_cabs_dag.yellow_cabs_upload manual__2024-02-09T18:21:53.472322+00:00 [queued]>
[2024-02-09T18:21:55.332+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-02-09T18:21:55.342+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): yellow_cabs_upload> on 2024-02-09 18:21:53.472322+00:00
[2024-02-09T18:21:55.347+0000] {standard_task_runner.py:60} INFO - Started process 71 to run task
[2024-02-09T18:21:55.367+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'yellow_cabs_dag', 'yellow_cabs_upload', 'manual__2024-02-09T18:21:53.472322+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/yellow_cabs_project.py', '--cfg-path', '/tmp/tmpnjqcia9i']
[2024-02-09T18:21:55.943+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask yellow_cabs_upload
[2024-02-09T18:21:56.035+0000] {task_command.py:423} INFO - Running <TaskInstance: yellow_cabs_dag.yellow_cabs_upload manual__2024-02-09T18:21:53.472322+00:00 [running]> on host 5a7c8003578a
[2024-02-09T18:21:56.139+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='yellow_cabs_dag' AIRFLOW_CTX_TASK_ID='yellow_cabs_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-02-09T18:21:53.472322+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-09T18:21:53.472322+00:00'
[2024-02-09T18:22:05.512+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/yellow_cabs_project.py", line 23, in yellow_cabs_upload
    df = pd.concat(new_table)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 372, in concat
    op = _Concatenator(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 407, in __init__
    raise TypeError(
TypeError: first argument must be an iterable of pandas objects, you passed an object of type "DataFrame"
[2024-02-09T18:22:05.519+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=yellow_cabs_dag, task_id=yellow_cabs_upload, execution_date=20240209T182153, start_date=20240209T182155, end_date=20240209T182205
[2024-02-09T18:22:05.525+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 12 for task yellow_cabs_upload (first argument must be an iterable of pandas objects, you passed an object of type "DataFrame"; 71)
[2024-02-09T18:22:05.596+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-09T18:22:05.603+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
